baseURL: https://www.kiel-koalas.de
title: Kiel Koalas AFC – Australian Football in Kiel
enableGitInfo: true
disableKinds:
- taxonomy
- taxonomyTerm
DefaultContentLanguage: de
languages:
  de:
    languageName: Deutsch
    weight: 10
  en:
    languageName: English
    weight: 20
