baseURL: https://www.australian-rules-football-kiel.de
title: Australian Rules Football in Kiel
enableGitInfo: true
disableKinds:
- taxonomy
- taxonomyTerm
DefaultContentLanguage: de
languages:
  de:
    languageName: Deutsch
    weight: 10
  en:
    languageName: English
    weight: 20
