name: Build and deploy website
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
      - name: Build
        run: hugo --minify
      - run: ls -l ${{ github.workspace }}
      - run: ls -l ${{ github.workspace }}/public